# -*- coding: utf-8 -*-
"""Cakeapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ywqafQ2AoxIieS7XNE_szSBNzUJqVHL
"""

import streamlit as st
import os

# Set up page config
st.set_page_config(page_title="Sugar Shade", page_icon="🍰", layout="wide")

# Load and display logo
logo_path = "/mnt/data/image.png"  # Change to your logo path
st.markdown(
    f"""
    <div style="text-align: center;">
        <img src="data:image/png;base64,{open(logo_path, "rb").read().encode("base64").decode()}" width="150">
    </div>
    """,
    unsafe_allow_html=True,
)

# Apply modern CSS styling
st.markdown(
    """
    <style>
        body {
            background-color: #F5F0FF; /* Light pastel purple */
            color: #333;
        }
        .stButton>button {
            background-color: #A48DFF !important;
            color: white !important;
            font-size: 16px !important;
            border-radius: 10px !important;
            padding: 10px 20px !important;
        }
        .stTextInput>div>div>input, .stSelectbox>div>div>select {
            border-radius: 8px !important;
            border: 2px solid #A48DFF !important;
            padding: 10px !important;
            font-size: 16px !important;
        }
        .box {
            border-radius: 12px;
            background-color: white;
            padding: 20px;
            margin: 15px 0;
            box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);
        }
        .title {
            font-size: 24px;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
        }
        .price {
            color: #A48DFF;
            font-weight: bold;
        }
    </style>
    """,
    unsafe_allow_html=True,
)

# Sidebar for navigation
st.sidebar.markdown("<h2 style='color: #A48DFF;'>📌 Menu</h2>", unsafe_allow_html=True)
menu_option = st.sidebar.radio("Go to", ["🏠 Home", "🛍️ Shop", "🛒 Cart"])

if menu_option == "🏠 Home":
    st.markdown("<h2 class='title'>Welcome to Sugar Shade 🍰</h2>", unsafe_allow_html=True)
    st.image("https://source.unsplash.com/600x400/?cake", caption="Delicious Cakes", use_column_width=True)
    st.markdown("<p style='font-size: 18px;'>Enjoy handmade, freshly baked cakes with delightful flavors.</p>", unsafe_allow_html=True)

elif menu_option == "🛍️ Shop":
    st.markdown("<h2 class='title'>🛍️ Shop Cakes</h2>", unsafe_allow_html=True)

    col1, col2, col3 = st.columns(3)

    with col1:
        st.image("https://source.unsplash.com/300x200/?black-forest-cake", use_column_width=True)
        st.markdown("<h4>Black Forest Cake</h4>", unsafe_allow_html=True)
        st.markdown("<p class='price'>IDR 210.000</p>", unsafe_allow_html=True)
        st.button("Add to Cart", key="black_forest")

    with col2:
        st.image("https://source.unsplash.com/300x200/?cupcake", use_column_width=True)
        st.markdown("<h4>Choco Cupcake</h4>", unsafe_allow_html=True)
        st.markdown("<p class='price'>IDR 60.000</p>", unsafe_allow_html=True)
        st.button("Add to Cart", key="choco_cupcake")

    with col3:
        st.image("https://source.unsplash.com/300x200/?bread", use_column_width=True)
        st.markdown("<h4>Milk Toast Bread</h4>", unsafe_allow_html=True)
        st.markdown("<p class='price'>IDR 40.000</p>", unsafe_allow_html=True)
        st.button("Add to Cart", key="milk_toast")

elif menu_option == "🛒 Cart":
    st.markdown("<h2 class='title'>🛒 My Cart</h2>", unsafe_allow_html=True)
    st.write("Black Forest Cake - IDR 210.000")
    st.write("Choco Cupcake (x3) - IDR 180.000")
    st.write("Milk Toast Bread (x2) - IDR 80.000")
    st.markdown("<h3 class='price'>Total: IDR 470.000</h3>", unsafe_allow_html=True)
    st.button("Checkout")